### ISSUE TITLE
Pausing Video from Plex Home Theater Causes Video to Eventually Stop Playing

### ISSUE THREAD

**Issue by dulguldur** [sharkone/BitTorrent.bundle#49] opened 2015-03-01 20:03 UTC
It seems every time I pause a video downloaded by Bittorrent plugin, the video eventually stops playing altogether (usually at some point afterwards during the video), that is, it abruptly returns to the video metadata information screen (i.e., the screen where after you push play, the video will attempt to load with a "Please wait" notice). 

Does anyone else experience this problem?

Running:
Plex Server 0.9.11.7 on Ubuntu Server 14.04.01 x32. 
Plex Home Theater 1.3.5.431-7966a4df on separate Win7 x64 computer.

Thanks again for this really cool bit of software!

**Comment by sharkone** [comment] 2015-03-01 20:09
How long do you keep it paused?

The plugin uses two different timeout values to limit unnecessary uploading. First one will pause the transfer after 30s (default value) of inactivity (pausing or even stopping the playback for instance). Resuming playback should resume the transfer properly.

The second timer (10min by default) will effectivement remove the transfer, most likely preventing resuming. This is used to stop seeding infinitely when you're finished watching your content.

So if you haven't changed the default values in the Preferences page, and you end up pausing playback for more than 10min, the problem you're describing can happen but is eventually by design.

If it bothers you, you can always tweak the value to your liking, but be aware that it will also mean that you'll keep seeding longer.

Hope that helped!

**Comment by dulguldur** [comment] 2015-03-04 20:25
I was told that the video just stopped playing without pausing. I'll try to tweak some of the timeout values and see what I can come up with.

Again, great piece of software! You pwn!

**Comment by sharkone** [comment] 2015-03-04 20:39
I will then close this issue. Feel free to reopen a new one with new repro steps if needed.

**Closed by sharkone** 2015-03-04 20:39 UTC
